spring.application.name=wyd-web

spring.datasource.url=jdbc:postgresql://localhost:5432/wyd_web
spring.datasource.username=wyd
spring.datasource.password=wyd

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.flyway.enabled=true