services:

  postgres:
    image: postgres:17
    container_name: wyd-web-postgres
    environment:
      POSTGRES_DB: wyd_web
      POSTGRES_USER: wyd
      POSTGRES_PASSWORD: wyd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: